### PR TITLE
Adds support and tests for purchases

### PR DESCRIPTION
**Pull request by ssbean**
One of my first PRs. Feedback welcome!

This adds support for the three purchase methods currently in beta on the [API docs](https://www.getdrip.com/docs/rest-api#purchases). While the properties, items, and other data options being passed via the API for the `create_purchase` method doesn't seem to be displaying anywhere in the interface, purchases do show up on the activity timeline and the lifetime value of a customer is updated. I'm hopeful that the rest of the information is being sent and stored correctly, and will be retrievable eventually.

As for the other two methods (pulling all purchases for a subscriber, and fetching an individual purchase) the API is currently returning a 415 error. I'm not sure if I should be doing something differently with the content type, but it should be defaulting to the gem standard, `application/vnd.api+json`. This leads me to think that there may be an issue with the API itself, but I'd like someone else to take a look before I submit anything to Drip.

### CODE REVIEW

**Comment by djreimer** [comment]
Thanks @ssbean! :star2: 

I will look into the 415 problem and try to get this merged soon.

**Comment by jrgifford** [comment]
Hi! Any update on this? I'm interested in building something with purchases.

**Comment by benwoodward** [comment]
This PR works on my machine. The only issue I could find is that the error response is not handled, for example, if you request a purchase that doesn't exist:

```ruby
[9] pry(main)> @client.purchase('email@example', 111111111)
NoMethodError: undefined method `keys' for "500":String
from /Users/ben/Dev/OSS/ssbean-drip-ruby/lib/drip/resource.rb:32:in `block in process'
```

**Comment by djreimer** [comment]
This now on master, thanks again @ssbean.

@benwoodward the 500 scenario should be all fixed up.

**Comment by ssbean** [comment]
Happy to help. Thanks for the polish, @djreimer!

**Comment by benwoodward** [comment]
Fantastic, thanks for your work!

**Pull request merged**
