### PR TITLE
Add delete_subscriber

### PR DESCRIPTION
**Pull request by sposinff**

### CODE REVIEW

**Comment by sposinff** [comment]
This is the first time I have forked.  Let me know if I did anything wrong or what not.

**Comment by sposinff** [comment]
Hello, I am just wondering what I need to do next?  The checks failed, but I think it is outside of my control as it is part of the build.

**Comment by broeken** [comment]
Would be great if this feature shipped some time soon, because I'd love to use it. The failed build looks like a random failure.

**Comment by djreimer** [comment]
Thanks! Sorry for the delay, this looks good to me.

**Comment by djreimer** [comment]
Version 0.0.7 has been released to Rubygems.

**Comment by sposinff** [comment]
👍

**Pull request merged**
