### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by RajRoR**

### CODE REVIEW

**Comment by RajRoR** [comment]
@djreimer Can you please merge this typo fix. This is related to my previous PR. This will make v0.0.8 stable

**Comment by djreimer** [comment]
Yes, will do. I wonder why tests didn't catch this 🤔

**Comment by djreimer** [comment]
I released v0.0.9.

**Comment by RajRoR** [comment]
Thanks @djreimer but I am seeing another problem. You have removed the initializer from `Tag` class. Thats not duplicate but we need that.

Default initilizer is processing the returned attributes (key-value), however, drip API returns an array of tags like: `['tag1', 'tag2']` so there will not be any keys in that. So, we don't need to `@attributes = process(@raw_attributes)`, instead we need `@attributes = @raw_attributes`

**Comment by djreimer** [comment]
Bah...thanks. I will fix that as well.

**Pull request merged**
